### ISSUE TITLE
.gitlab-ci.yml is missing

### ISSUE THREAD

**Issue by iamutaki** [satyakresna/catatan-penjelajahtekno#1]
i cannot find .gitlab-ci.yml on your gist.

**Comment by kresnasatya** [comment]
Hi there, you can check in my updated commit: 8d0b62c181ff3fd721dfd5828b9f47f339da454e. Thank you for report.

**Comment by iamutaki** [comment]
thanks for your response, hmm i read your article and its really good and helpfully dumb people like :D. thank you so much bro :D.
